# Funding
# Enable the buttons you want on the repo's Sponsor page.
github: [miruamel]
# patreon: miruamel
# open_collective: miruamel
# ko_fi: miruamel
# tidelift: miruamel/zhi
# community_bridge: miruamel
# liberapay: miruamel
# issuehunt: miruamel
# lfx_crowdfunding: miruamel
# polar: miruamel
# buy_me_a_coffee: miruamel
# thanks_dev: miruamel
# custom: https://zhi.dev/sponsor
